### ISSUE TITLE
Proper Resource Limits for the Kluster Pods

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#13]
We should have resource limits for the customer components in the parent cluster in place from the start.

At the moment I just added this for every pod:
```
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```
This obviously is too low because the components start failing with zero payload on them.
We need same sane defaults and probably also a something in the TPR to modify those. The customer should not be able to modify those so they should be outside `Spec`. See #3
