### ISSUE TITLE
Cleanup and enhance spec

### ISSUE THREAD

**Issue by databus23** [sapcc/kubernikus#3]
Right now the TPR is very basic:
```
apiVersion: kubernikus.sap.cc/v1
kind: Kluster
metadata:
  annotations:
    creator: D062284
  labels:
    account: 8b25871959204ff1a27605b7bcf873f7
  name: test-8b25871959204ff1a27605b7bcf873f7

spec:
  account: 8b25871959204ff1a27605b7bcf873f7
  name: test
status:
  message: Creating Cluster
  state: Creating
```

So basically the user can only choose the name of the cluster.

A few things I have in mind:

* The `Spec` probably needs fields for:
  * Specifying the desired kubernetes version
  * Specifying the number of nodes (kubelets), including size, AZ
  * Specifying the Router and subnet ID all nodes should be deployed to
  * Specifying the region (in case we have more then one)
  * ...
* We also need a place to store runtime state we generate about the cluster (probaply `Status` but I'm not sure this fits 100%). At minimum we need to store
  * The open stack server user name, password and domain, author
  * All CA certs and keys
