### ISSUE TITLE
Add an attribute to define auto update maintenance window

### ISSUE THREAD

**Issue by kayrus** [sapcc/kubernikus#521]
https://coreos.com/os/docs/latest/update-strategies.html#auto-updates-with-a-maintenance-window

It would be nice if Kubernikus can allow to define a node pool attribute to specify maintenance windows, explained in the doc above.

```yaml
# This config is meant to be consumed by the config transpiler, which will
# generate the corresponding Ignition config. Do not pass this config directly
# to instances of Container Linux.

locksmith:
  reboot_strategy: reboot
  window_start: Thu 04:00
  window_length: 1h
```
